<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.Core" Version="2.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatDomain\Chat.Domain.csproj" />
  </ItemGroup>

</Project>
